# Multiple imputation by chained equations (MICE)

In [33]:
# Cargar bibliotecas
import seaborn as sns
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [34]:
# Cargar el dataset de Titanic desde seaborn
titanic = sns.load_dataset('titanic')

In [36]:
# Mostrar primeros valores
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [37]:
# Check missing data
print(titanic.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [38]:
# Vamos a imputar los valores faltantes de la columna 'age' (edad)
# Seleccionamos un subconjunto de columnas para el ejemplo
data = titanic[['age', 'fare', 'pclass', 'sex']]

# Convertimos las variables categóricas en variables dummy (la variable 'sex' es categórica)
data = pd.get_dummies(data, drop_first=True)

data.head(20)

     age     fare  pclass  sex_male
0   22.0   7.2500       3      True
1   38.0  71.2833       1     False
2   26.0   7.9250       3     False
3   35.0  53.1000       1     False
4   35.0   8.0500       3      True
5    NaN   8.4583       3      True
6   54.0  51.8625       1      True
7    2.0  21.0750       3      True
8   27.0  11.1333       3     False
9   14.0  30.0708       2     False
10   4.0  16.7000       3     False
11  58.0  26.5500       1     False
12  20.0   8.0500       3      True
13  39.0  31.2750       3      True
14  14.0   7.8542       3     False
15  55.0  16.0000       2     False
16   2.0  29.1250       3      True
17   NaN  13.0000       2      True
18  31.0  18.0000       3     False
19   NaN   7.2250       3     False

In [39]:
# Crear el imputador MICE (IterativeImputer)
imputer = IterativeImputer(max_iter=10, random_state=0)

In [40]:
# Imputar los valores faltantes
data_imputed = pd.DataFrame(imputer.fit_transform(data), columns=data.columns)

In [41]:
# Mostrar los datos originales con valores faltantes
print("Datos originales (con valores faltantes):")
data.head(30)

Datos originales (con valores faltantes):

     age      fare  pclass  sex_male
0   22.0    7.2500       3      True
1   38.0   71.2833       1     False
2   26.0    7.9250       3     False
3   35.0   53.1000       1     False
4   35.0    8.0500       3      True
5    NaN    8.4583       3      True
6   54.0   51.8625       1      True
7    2.0   21.0750       3      True
8   27.0   11.1333       3     False
9   14.0   30.0708       2     False
10   4.0   16.7000       3     False
11  58.0   26.5500       1     False
12  20.0    8.0500       3      True
13  39.0   31.2750       3      True
14  14.0    7.8542       3     False
15  55.0   16.0000       2     False
16   2.0   29.1250       3      True
17   NaN   13.0000       2      True
18  31.0   18.0000       3     False
19   NaN    7.2250       3     False
20  35.0   26.0000       2      True
21  34.0   13.0000       2      True
22  15.0    8.0292       3     False
23  28.0   35.5000       1      True
24   8.0   21.0750       3     False
25  38.0   31.3875       3     False
26   NaN    7.2250       3      True
27  19.0  263.0000       1      True
28   NaN    7.8792       3     False
29   NaN    7.8958       3      True

In [42]:
# Mostrar los datos después de la imputación múltiple (MICE)
print("\nDatos después de la imputación múltiple (MICE):")
data_imputed.head(30)

Datos después de la imputación múltiple (MICE):

          age      fare  pclass  sex_male
0   22.000000    7.2500     3.0       1.0
1   38.000000   71.2833     1.0       0.0
2   26.000000    7.9250     3.0       0.0
3   35.000000   53.1000     1.0       0.0
4   35.000000    8.0500     3.0       1.0
5   26.082704    8.4583     3.0       1.0
6   54.000000   51.8625     1.0       1.0
7    2.000000   21.0750     3.0       1.0
8   27.000000   11.1333     3.0       0.0
9   14.000000   30.0708     2.0       0.0
10   4.000000   16.7000     3.0       0.0
11  58.000000   26.5500     1.0       0.0
12  20.000000    8.0500     3.0       1.0
13  39.000000   31.2750     3.0       1.0
14  14.000000    7.8542     3.0       0.0
15  55.000000   16.0000     2.0       0.0
16   2.000000   29.1250     3.0       1.0
17  33.850204   13.0000     2.0       1.0
18  31.000000   18.0000     3.0       0.0
19  22.070708    7.2250     3.0       0.0
20  35.000000   26.0000     2.0       1.0
21  34.000000   13.0000     2.0       1.0
22  15.000000    8.0292     3.0       0.0
23  28.000000   35.5000     1.0       1.0
24   8.000000   21.0750     3.0       0.0
25  38.000000   31.3875     3.0       0.0
26  26.127637    7.2250     3.0       1.0
27  19.000000  263.0000     1.0       1.0
28  22.046873    7.8792     3.0       0.0
29  26.103198    7.8958     3.0       1.0

# Exercise 1
Use MICE on the Diabetes (Scikit-learn) dataset to fill in missing values.

# Exercise 2
Use MICE on the Planets (seaborn) dataset to fill in missing values.